import Link from 'next/link';

export default function AboutPage() {
  return (
    <div className="min-h-screen bg-gradient-to-br from-blue-900 via-purple-900 to-black">
      <header className="bg-black bg-opacity-50 backdrop-blur-sm border-b border-white border-opacity-10">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-6">
          <Link href="/" className="text-2xl font-bold text-white hover:text-gray-300">
            ← AI Radio 2525
          </Link>
        </div>
      </header>

      <main className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-12">
        <div className="bg-white bg-opacity-10 backdrop-blur-lg rounded-lg p-8 border border-white border-opacity-20 text-white space-y-6">
          <h1 className="text-4xl font-bold mb-8">About AI Radio 2525</h1>

          <section>
            <h2 className="text-2xl font-bold mb-4">Welcome to the Future</h2>
            <p className="text-gray-300 leading-relaxed">
              AI Radio 2525 is an experimental radio station that broadcasts from the year 2525.
              Every segment, every word, every piece of content is generated by artificial intelligence
              and synthesized in real-time, creating a unique listening experience that explores what
              radio might be like 500 years from now.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold mb-4">The Concept</h2>
            <p className="text-gray-300 leading-relaxed mb-4">
              Imagine tuning into a radio station from the distant future. What would people be talking about?
              What events would shape their world? How would culture, technology, and society have evolved?
            </p>
            <p className="text-gray-300 leading-relaxed">
              AI Radio 2525 answers these questions through AI-generated content that creates a coherent,
              immersive world set 500 years in the future. Using advanced language models and text-to-speech
              technology, we create news broadcasts, cultural commentary, interviews, and more—all set in
              this speculative future.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold mb-4">Features</h2>
            <ul className="space-y-2 text-gray-300">
              <li className="flex items-start">
                <span className="mr-2">🎙️</span>
                <span><strong>100% AI Generated:</strong> All content created by Claude AI</span>
              </li>
              <li className="flex items-start">
                <span className="mr-2">🔊</span>
                <span><strong>Natural Voice Synthesis:</strong> Powered by Piper TTS</span>
              </li>
              <li className="flex items-start">
                <span className="mr-2">📡</span>
                <span><strong>24/7 Broadcasting:</strong> Continuous, scheduled programming</span>
              </li>
              <li className="flex items-start">
                <span className="mr-2">🌍</span>
                <span><strong>Coherent Worldbuilding:</strong> Consistent universe across all segments</span>
              </li>
              <li className="flex items-start">
                <span className="mr-2">📰</span>
                <span><strong>Diverse Content:</strong> News, culture, technology, interviews, and more</span>
              </li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-bold mb-4">The Team</h2>
            <p className="text-gray-300 leading-relaxed">
              AI Radio 2525 is an experimental project exploring the intersection of AI, creativity,
              and broadcasting. It demonstrates the potential of large language models and modern
              text-to-speech systems to create engaging, coherent content at scale.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold mb-4">Open Source</h2>
            <p className="text-gray-300 leading-relaxed mb-4">
              AI Radio 2525 is open source and built with modern technologies. The entire system—from
              content generation to audio processing to broadcasting—is available for others to learn
              from and build upon.
            </p>
            <Link
              href="/how-it-works"
              className="inline-block px-6 py-3 bg-blue-600 hover:bg-blue-700 rounded-lg font-medium transition"
            >
              Learn How It Works →
            </Link>
          </section>
        </div>
      </main>
    </div>
  );
}
